### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'void 

### ISSUE THREAD

**Issue by NBSDEVApp** [xtonousou/xSoundBoardHD#20]
Hi,
I have lot of same error when i use signed apk on google play

> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setSearchableInfo(android.app.SearchableInfo)' on a null object reference
FATAL EXCEPTION: main
Process: pro.nbsdev.doyouknowtheway, PID: 11121
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setSearchableInfo(android.app.SearchableInfo)' on a null object reference
	at pro.nbsdev.doyouknowtheway.MainActivity.a(Unknown Source)
	at pro.nbsdev.doyouknowtheway.MainActivity.onCreateOptionsMenu(Unknown Source)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2856)
	at android.support.v4.a.j.onCreatePanelMenu(Unknown Source)
	at android.support.v7.view.i.onCreatePanelMenu(Unknown Source)
	at android.support.v7.app.h$b.onCreatePanelMenu(Unknown Source)
	at android.support.v7.view.i.onCreatePanelMenu(Unknown Source)
	at android.support.v7.app.q.i(Unknown Source)
	at android.support.v7.app.q$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

Thanks for helping me
NBSDEV

**Comment by NBSDEVApp** [comment]
And when i launch app on my google play beta i have launch crash

**Comment by xtonousou** [comment]
Refer to [here](https://stackoverflow.com/questions/27335608/errors-after-building-apk). Modify `build.gradle` properly.

**Comment by xtonousou** [comment]
Missing information. Closing.
